server:
  port: 8000

spring:
  cloud:
    stream:
      bindings:
        input:
            destination:  test
            content-type: application/json
      kafka:
        binder:
          zkNodes: localhost
          brokers: localhost