server:
  port: 8000

spring:
  cloud:
    stream:
      bindings:
        input:
            destination:  test
            content-type: application/json
            binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: username
                password: password
                virtual-host: /